line-length = 100
target-version = "py310"

[lint]
select = ["E", "F", "I", "UP", "B"]
ignore = ["E501"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint.per-file-ignores]
"**/*.ipynb" = ["E402", "E703", "B018"]
