[project]
name = "notebooks"
version = "0.1.0"
description = "Collection of notebooks and experiments"
requires-python = ">=3.10"
dependencies = [
	"ipykernel>=7.2.0",
	"jupyter>=1.0.0",
	"matplotlib>=3.5.2",
	"networkx>=2.8.2",
	"numpy>=1.22.4",
	"plotly>=6.5.2",
	"pykernel>=0.1.6",
]

[dependency-groups]
dev = [
	"ruff>=0.8.0",
	"ty>=0.0.1a14",
]
