name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
          
      - uses: fortierq/add-binder-link-action@v1
        with:
          force: 'true'
          env: 'fortierq/notebooks'
          branch-env: 'master'

      - name: Build the JupyterLite site
        run: |
          jupyter lite build --files nb
          
      - name: Upload (dist)
        uses: actions/upload-artifact@v2
        with:
          name: jupyterlite-demo dist ${{ github.run_number }}
          path: ./_output

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - uses: actions/download-artifact@v2
        with:
          name: jupyterlite-demo dist ${{ github.run_number }}
          path: ./dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
